sudo: false

language: cpp

matrix:
  include:
    - os: linux 
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
    - libxml2-dev
    - libfltk1.3-dev
    - fluid
    - libcpptest-dev
    - libjpeg-dev
    - libglm-dev
    - libeigen3-dev
    - libcminpack-dev
    - libglew-dev
script:
 - mkdir build; cd build
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject;
   fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_CPPTEST=true -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_EIGEN=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject; 
   fi
 - make
 - ~/OpenVSP_Install/vspscript -script ../examples/scripts/TestAll.vspscript
 - ~/OpenVSP_Install/apitest
