sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - libxml2-dev
    - libfltk1.3-dev
    - libcpptest-dev
    - libjpeg-dev
    - libglm-dev
    - libeigen3-dev
    - libcminpack-dev
    - libglew-dev
script:
 - mkdir build; cd build
 - cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_CPPTEST=true -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_EIGEN=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true ../SuperProject
 - make
 - ./OpenVSP-prefix/src/OpenVSP-build/src/vsp/vspscript -script ../examples/scripts/TestAll.vspscript
